export default {
  TEST_ACTION: "JOB_TEST_ACTION",
  TEST_ACTION_PROGRESS: "TEST_ACTION_PROGRESS",
  TEST_ACTION_COMPLETED: "JOB_TEST_ACTION_COMPLETED",

  SEARCH_JOBS: "SEARCH_JOBS",
  SEARCH_JOBS_IN_PROGRESS: "SEARCH_JOBS_IN_PROGRESS",
  SEARCH_JOBS_COMPLETED: "SEARCH_JOBS_COMPLETED"
};
